networks:
  frontend:
  backend:

volumes:
  pihole:
  portainer:

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
      - 9000:9000
    networks:
      - frontend
      - backend

  ndi-discovery:
    container_name: ndi-discovery
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ./ndi-discovery/ndi-config.json:/root/.ndi/ndi-config.json