# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
networks:
  frontend:
  backend:

volumes:
  pihole:
  portainer:

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
      - 9000:9000
    networks:
      - frontend
      - backend

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "67:67/udp"
      - "123:123/udp"
    environment:
      TZ: 'Europe/Dublin'
      FTLCONF_webserver_api_password: 'Love Life Apples'
      FTLCONF_dns_listeningMode: 'ALL'
    volumes:
      - pihole:/etc/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped

  ndi-discovery:
    container_name: ndi-discovery
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ./ndi-discovery/ndi-config.json:/root/.ndi/ndi-config.json